version: "3.8"
services:
  db:
    image: mongo:6.0
    container_name: db
    restart: always
    environment:
      MONGO_URI:

  node-api:
    build:
      context: ./weather_app/
      dockerfile: Dockerfile
    container_name: node-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_CONNECTION_STRING:
      API_KEY:
    depends_on:
      - db
