name: Test Suite

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened]

jobs:
  server-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: server
        run: npm ci

      - name: Run Test Suite
        working-directory: server
        run: npm run test
